apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k8-benetis/nkz
    targetRevision: HEAD
    path: k8s/vpn
  destination:
    server: https://kubernetes.default.svc
    namespace: nekazari
  # Secret nekazari-iot-ca-secret is not in Git (created manually); prune disabled so ArgoCD won't delete it
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
